Debian Wheezy template addition and refactoring to allow Whonix TEMPLATE_FLAVOR

diff --git a/prepare_image b/prepare_image
--- a/prepare_image
+++ b/prepare_image
@@ -1,6 +1,10 @@
-#!/bin/sh
+#!/bin/bash
+#XXX: use bash #!/bin/sh
 
-export IMG=$1
+# ------------------------------------------------------------------------------
+# Configurations
+# ------------------------------------------------------------------------------
+export IMG="$1"
 export LC_ALL=POSIX
 
 RETCODE=0
@@ -8,49 +12,70 @@ RETCODE=0
 : ${DIST=fc14}
 
 . ./builder_setup >/dev/null
+. ./umount.sh >/dev/null
 
-set -e
+if [ "$VERBOSE" -ge 2 -o "$DEBUG" == "1" ]; then
+    set -x
+else
+    set -e
+fi
 
 if ! [ $# -eq 1 ]; then
-echo "usage $0 <img_file_name>"
-exit
+    echo "usage $0 <img_file_name>"
+    exit
 fi
 
 if [ "$VERBOSE" == "1" ]; then
-	export YUM_OPTS="$YUM_OPTS -q"
+    export YUM_OPTS="$YUM_OPTS -q"
 fi
 
+# ------------------------------------------------------------------------------
+# Prepare for mount
+# ------------------------------------------------------------------------------
 echo "-> Preparing instalation of $DIST template..."
-$SCRIPTSDIR/00_prepare.sh
+"$SCRIPTSDIR/00_prepare.sh"
 
-if [ -f $IMG ]; then
-	echo "-> Image file already exists, assuming *update*..."
-	mount -o loop $IMG mnt || exit 1
-	export INSTALLDIR=`pwd`/mnt/
-	trap "umount $INSTALLDIR" EXIT
+# ------------------------------------------------------------------------------
+# Mount image and install core OS
+# ------------------------------------------------------------------------------
+if [ -f "$IMG" ]; then
+    echo "-> Image file already exists, assuming *update*..."
+    mount -o loop "$IMG" mnt || exit 1
+    export INSTALLDIR="`pwd`/mnt/"
+    trap "umount_image ${INSTALLDIR::-1}" EXIT
+
+    # XXX: Temp; just for debugging
+    if ! [ -f "$INSTALLDIR/tmp/.prepared_debootstrap" ]; then
+        "$SCRIPTSDIR/01_install_core.sh"
+    fi
 else
+    echo "-> Initializing empty image..."
+    truncate -s 10G "$IMG" || exit 1
 
-	echo "-> Initializing empty image..."
-	truncate -s 10G $IMG || exit 1
+    echo "-> Creating filesystem..."
+    mkfs.ext4 -q -F "$IMG" || exit 1
 
-	echo "-> Creating filesystem..."
-	mkfs.ext4 -q -F $IMG || exit 1
+    mkdir -p mnt
+    mount -o loop "$IMG" mnt || exit 1
 
-	mkdir -p mnt
-	mount -o loop $IMG mnt || exit 1
+    export INSTALLDIR="`pwd`/mnt/"
+    trap "umount_image ${INSTALLDIR::-1}" EXIT
 
-	export INSTALLDIR=`pwd`/mnt/
-
-	trap "umount $INSTALLDIR" EXIT
-
-	$SCRIPTSDIR/01_install_core.sh
+    "$SCRIPTSDIR/01_install_core.sh"
 fi
 
+# ------------------------------------------------------------------------------
+# Install package groups
+# ------------------------------------------------------------------------------
 echo "-> Installing package groups..."
-$SCRIPTSDIR/02_install_groups.sh
+"$SCRIPTSDIR/02_install_groups.sh"
 
+# ------------------------------------------------------------------------------
+# Cleanup
+# ------------------------------------------------------------------------------
 trap - EXIT
+
 echo "-> Unmounting prepared_image..."
-sudo umount $INSTALLDIR
+umount_image "$INSTALLDIR" || :
 
 exit $RETCODE
