qubes_image: split into *_appvm and *_netvm

diff --git a/qubeize_image_netvm b/qubeize_image_netvm
--- a/qubeize_image_netvm
+++ b/qubeize_image_netvm
@@ -2,20 +2,20 @@
 
 CLEANIMG=$1
 NAME=$2
-IS_NETVM=$3
 
 if [ $# -eq 0 ]; then
 echo "usage $0 <clean_image_file> <template_name>"
-echo "usage $0 <clean_image_file> <template_name> netvm"
 exit
 fi
 
 if [ x$CLEANIMG = x ]; then
 echo "Image file not specified!"
+exit 1
 fi
 
 if [ x$NAME = x ]; then
 echo "Name not given!"
+exit 1
 fi
 
 ID=$(id -ur)
@@ -36,7 +36,7 @@ mkdir -p mnt
 mount -o loop,offset=$((63*512)) qubeized_images/$NAME-root.img mnt || exit 1
 
 echo "--> Installing RPMs..."
-rpm --force --root=$(pwd)/mnt -ihv rpms_to_install/*
+rpm --force --nodeps --root=$(pwd)/mnt -ihv rpms_to_install_netvm/*
 
 
 echo "--> Copying the Apps Menu shortcuts..."
@@ -45,21 +45,10 @@ APPSTEMPL=qubeized_images/$NAME-apps.templates
 mkdir -p $APPSORIG
 cp -r $(pwd)/mnt/usr/share/applications/* $APPSORIG
 
-if [ x$IS_NETVM != x ]; then
-    if ! [ -d netvm/apps.templates ] ; then
-        echo "--> ERROR: Missing netvm/apps.templates directory."
-        exit 1
-    fi
-else
-    echo "--> Createing the Apps Menu templates..."
-    ./create_apps_templates.sh $APPSORIG $APPSTEMPL
+if ! [ -d netvm/apps.templates ] ; then
+echo "--> ERROR: Missing netvm/apps.templates directory."
+exit 1
 fi
-
-if [ x$IS_NETVM == x ]; then
-    echo "--> Installing 3rd party apps"
-    ./add_3rd_party_software.sh
-fi
-
 
 echo "--> Unmounting $IMG"
 umount mnt
